import turtle

t = turtle.Turtle()
screen = turtle.Screen()
screen.setup(800,800)
screen.bgcolor("red")
t2=turtle.Turtle()

t2.hideturtle()
t2.fillcolor('red')
t2.penup()
t2.goto(0,100)

t.penup()
t.goto(0,50)
t.pendown()
t.write("Personal Information",font=("Arial",24,"bold"),align="center")
t.penup()
t.goto(0,-50)
t.pendown()
t.write("Michael Haas",font=("Arial",24,"bold"),align="center")

t.penup()
t.goto(-250,-50)
t.pendown()
t.fillcolor("blue")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

t.penup()
t.goto(250,-50)
t.pendown()
t.fillcolor("orange")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

enter = input("press enter to start")
screen.bgcolor('blue')
t.clear()

t2.hideturtle()
t2.fillcolor('red')
t2.penup()
t2.goto(0,100)

t.penup()
t.goto(0,50)

t.write("Favorite Food",font=("Arial",24,"bold"),align="center")
t.penup()
t.goto(0,-50)

t.write("Pizza",font=("Arial",24,"bold"),align="center")

t2.goto(100,200)
turtle.addshape('pizza.gif')
t2.shape('pizza.gif')
a = t2.stamp()
t.goto(0,0)

t2.goto(-100,200)
turtle.addshape('cheesepizza.gif')
t2.shape('cheesepizza.gif')
b = t2.stamp()
t.goto(0,0)


t.penup()
t.goto(-250,-50)
t.pendown()
t.pencolor("brown")
t.fillcolor("yellow")
t.begin_fill()
t.circle(50,360)
t.end_fill()

t.penup()
t.goto(250,-50)
t.pendown()
t.pencolor("brown")
t.fillcolor("yellow")
t.begin_fill()
t.circle(50,360)
t.end_fill()

enter = input("press enter to start")
screen.bgcolor('Green')
t.clear()
t2.clear()

t2.hideturtle()
t2.fillcolor('red')
t2.penup()
t2.goto(0,100)

t.penup()
t.goto(0,50)

t.write("Favorite Hobbies",font=("Arial",24,"bold"),align="center")
t.penup()
t.goto(0,-50)

t.write("Skiing, Fishing, camping, biking",font=("Arial",15,"bold"),align="center")

t2.goto(100,200)
turtle.addshape('ski.gif')
t2.shape('ski.gif')
a = t2.stamp()
t.goto(0,0)

t2.goto(-100,200)
turtle.addshape('fishing.gif')
t2.shape('fishing.gif')
b = t2.stamp()
t.goto(0,0)

t.penup()
t.goto(-250,-50)
t.pendown()
t.fillcolor("pink")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

t.penup()
t.goto(250,-50)
t.pendown()
t.fillcolor("yellow")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

enter = input("press enter to start")
screen.bgcolor('yellow')
t.clear()
t2.clear()

t2.hideturtle()
t2.fillcolor('red')
t2.penup()
t2.goto(0,100)

t.penup()
t.goto(0,50)

t.write("Favorite Movie",font=("Arial",24,"bold"),align="center")
t.penup()
t.goto(0,-50)

t.write("Goonies",font=("Arial",24,"bold"),align="center")

t2.goto(100,200)
turtle.addshape('goonies.gif')
t2.shape('goonies.gif')
a = t2.stamp()
t.goto(0,0)

t2.goto(-100,200)
turtle.addshape('GooniesHome.gif')
t2.shape('GooniesHome.gif')
b = t2.stamp()
t.goto(0,0)

t.penup()
t.goto(-250,-50)
t.pendown()
t.pencolor("brown")
t.fillcolor("green")
t.begin_fill()
t.circle(50,360)
t.end_fill()

t.penup()
t.goto(250,-50)
t.pendown()
t.pencolor("brown")
t.fillcolor("blue")
t.begin_fill()
t.circle(50,360)
t.end_fill()

enter = input("press enter to start")
screen.bgcolor('blue')
t.clear()
t2.clear()

t2.hideturtle()
t2.fillcolor('teal')
t2.penup()
t2.goto(0,100)

t.penup()
t.goto(0,50)

t.write("Favorite Sport",font=("Arial",24,"bold"),align="center")
t.penup()
t.goto(0,-50)

t.write("Soccer, football",font=("Arial",24,"bold"),align="center")

t2.goto(100,200)
turtle.addshape('Football.gif')
t2.shape('Football.gif')
a = t2.stamp()
t.goto(0,0)

t2.goto(-100,200)
turtle.addshape('Soccer.gif')
t2.shape('Soccer.gif')
b = t2.stamp()
t.goto(0,0)

t.penup()
t.goto(-250,-50)
t.pendown()
t.fillcolor("red")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

t.penup()
t.goto(250,-50)
t.pendown()
t.fillcolor("orange")
t.begin_fill()
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.forward(50)
t.left(90)
t.end_fill()

turtle.done()